//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortniteBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FortniteBot.Resources.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à default.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the account.
        /// </summary>
        internal static string accname {
            get {
                return ResourceManager.GetString("accname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an API generated image with all the stats.
        /// </summary>
        internal static string addimage {
            get {
                return ResourceManager.GetString("addimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This command can only be used by a server admin..
        /// </summary>
        internal static string admincommand {
            get {
                return ResourceManager.GetString("admincommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language defined to.
        /// </summary>
        internal static string changelang1 {
            get {
                return ResourceManager.GetString("changelang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use the command to again to change it..
        /// </summary>
        internal static string changelang2 {
            get {
                return ResourceManager.GetString("changelang2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deaths.
        /// </summary>
        internal static string deaths {
            get {
                return ResourceManager.GetString("deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à News are empty or do not exist.
        /// </summary>
        internal static string emptynews {
            get {
                return ResourceManager.GetString("emptynews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gamepad.
        /// </summary>
        internal static string gamepad {
            get {
                return ResourceManager.GetString("gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games played.
        /// </summary>
        internal static string gplayed {
            get {
                return ResourceManager.GetString("gplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kills.
        /// </summary>
        internal static string kills {
            get {
                return ResourceManager.GetString("kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard / Mouse.
        /// </summary>
        internal static string kmouse {
            get {
                return ResourceManager.GetString("kmouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is not valid. Available languages are.
        /// </summary>
        internal static string langnotvalid {
            get {
                return ResourceManager.GetString("langnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lifetime.
        /// </summary>
        internal static string lifetime {
            get {
                return ResourceManager.GetString("lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mandatory.
        /// </summary>
        internal static string mandatory {
            get {
                return ResourceManager.GetString("mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest Battle Royale News.
        /// </summary>
        internal static string newsbr {
            get {
                return ResourceManager.GetString("newsbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show news only for Battle Royale or Save the World.
        /// </summary>
        internal static string newsparam {
            get {
                return ResourceManager.GetString("newsparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest Save The World News.
        /// </summary>
        internal static string newsstw {
            get {
                return ResourceManager.GetString("newsstw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist or has no stats.
        /// </summary>
        internal static string noexist {
            get {
                return ResourceManager.GetString("noexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optionnal.
        /// </summary>
        internal static string optionnal {
            get {
                return ResourceManager.GetString("optionnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à playerAccount.
        /// </summary>
        internal static string paccount {
            get {
                return ResourceManager.GetString("paccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefered game style is.
        /// </summary>
        internal static string preferedgs {
            get {
                return ResourceManager.GetString("preferedgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stats are private.
        /// </summary>
        internal static string pstats {
            get {
                return ResourceManager.GetString("pstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ratio K/D.
        /// </summary>
        internal static string ratio {
            get {
                return ResourceManager.GetString("ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à season.
        /// </summary>
        internal static string season {
            get {
                return ResourceManager.GetString("season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show stats from current Season, or for the all lifetime.
        /// </summary>
        internal static string showstats {
            get {
                return ResourceManager.GetString("showstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats for account.
        /// </summary>
        internal static string statsfor {
            get {
                return ResourceManager.GetString("statsfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 3.
        /// </summary>
        internal static string top3 {
            get {
                return ResourceManager.GetString("top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5.
        /// </summary>
        internal static string top5 {
            get {
                return ResourceManager.GetString("top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tablet / Phone.
        /// </summary>
        internal static string tphone {
            get {
                return ResourceManager.GetString("tphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Victories.
        /// </summary>
        internal static string victories {
            get {
                return ResourceManager.GetString("victories", resourceCulture);
            }
        }
    }
}
