//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortniteBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FortniteBot.Resources.FR", typeof(FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à par défaut.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du compte.
        /// </summary>
        internal static string accname {
            get {
                return ResourceManager.GetString("accname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajoute une image génerée par l&apos;API.
        /// </summary>
        internal static string addimage {
            get {
                return ResourceManager.GetString("addimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette commande ne peut être utilisée que par un Admin..
        /// </summary>
        internal static string admincommand {
            get {
                return ResourceManager.GetString("admincommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue définie sur.
        /// </summary>
        internal static string changelang1 {
            get {
                return ResourceManager.GetString("changelang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisez la commande une nouvelle fois pour changer..
        /// </summary>
        internal static string changelang2 {
            get {
                return ResourceManager.GetString("changelang2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Morts.
        /// </summary>
        internal static string deaths {
            get {
                return ResourceManager.GetString("deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les news sont vides ou n&apos;existent pas.
        /// </summary>
        internal static string emptynews {
            get {
                return ResourceManager.GetString("emptynews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manette.
        /// </summary>
        internal static string gamepad {
            get {
                return ResourceManager.GetString("gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties jouées.
        /// </summary>
        internal static string gplayed {
            get {
                return ResourceManager.GetString("gplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tués.
        /// </summary>
        internal static string kills {
            get {
                return ResourceManager.GetString("kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clavier / Souris.
        /// </summary>
        internal static string kmouse {
            get {
                return ResourceManager.GetString("kmouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;est pas valide. Les langues disponibles sont.
        /// </summary>
        internal static string langnotvalid {
            get {
                return ResourceManager.GetString("langnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lifetime.
        /// </summary>
        internal static string lifetime {
            get {
                return ResourceManager.GetString("lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obligatoire.
        /// </summary>
        internal static string mandatory {
            get {
                return ResourceManager.GetString("mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernières nouvelles Battle Royale.
        /// </summary>
        internal static string newsbr {
            get {
                return ResourceManager.GetString("newsbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir seulement les news Battle Royale ou Save the World.
        /// </summary>
        internal static string newsparam {
            get {
                return ResourceManager.GetString("newsparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernières nouvelles Save the World.
        /// </summary>
        internal static string newsstw {
            get {
                return ResourceManager.GetString("newsstw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;existe pas ou n&apos;a pas de stats.
        /// </summary>
        internal static string noexist {
            get {
                return ResourceManager.GetString("noexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optionnel.
        /// </summary>
        internal static string optionnal {
            get {
                return ResourceManager.GetString("optionnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à compteDuJoueur.
        /// </summary>
        internal static string paccount {
            get {
                return ResourceManager.GetString("paccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode de jeu préferé est.
        /// </summary>
        internal static string preferedgs {
            get {
                return ResourceManager.GetString("preferedgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à : Les statistiques sont privées.
        /// </summary>
        internal static string pstats {
            get {
                return ResourceManager.GetString("pstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ratio Tués/Morts.
        /// </summary>
        internal static string ratio {
            get {
                return ResourceManager.GetString("ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à season.
        /// </summary>
        internal static string season {
            get {
                return ResourceManager.GetString("season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affiche les stats de la saison, ou à vie.
        /// </summary>
        internal static string showstats {
            get {
                return ResourceManager.GetString("showstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats pour le compte.
        /// </summary>
        internal static string statsfor {
            get {
                return ResourceManager.GetString("statsfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 3.
        /// </summary>
        internal static string top3 {
            get {
                return ResourceManager.GetString("top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5.
        /// </summary>
        internal static string top5 {
            get {
                return ResourceManager.GetString("top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tablette / Téléphone.
        /// </summary>
        internal static string tphone {
            get {
                return ResourceManager.GetString("tphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisation.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Victoires.
        /// </summary>
        internal static string victories {
            get {
                return ResourceManager.GetString("victories", resourceCulture);
            }
        }
    }
}
